In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

from sklearn.metrics import confusion_matrix, roc_auc_score, roc_curve, auc, accuracy_score, f1_score, precision_score, recall_score

from xgboost import XGBClassifier

import warnings
warnings.filterwarnings("ignore")

In [5]:
PATH = "/content/drive/MyDrive/Datasets/wbcatt"

df = pd.read_csv(f"{PATH}/pbc_attr_v1_train.csv")
df.head()

        label cell_size cell_shape  ... granule_type granule_colour granularity
0  Neutrophil       big      round  ...        small           pink         yes
1  Neutrophil       big  irregular  ...        small           pink         yes
2  Neutrophil       big  irregular  ...        small           pink         yes
3  Neutrophil       big  irregular  ...        small           pink         yes
4  Neutrophil     small      round  ...        small           pink         yes

[5 rows x 12 columns]

In [6]:
df.shape

(6169, 12)

In [7]:
df["label"].value_counts()

label
Neutrophil    1984
Eosinophil    1876
Monocyte       829
Basophil       744
Lymphocyte     736
Name: count, dtype: int64

In [8]:
df.isnull().sum()

label                        0
cell_size                    0
cell_shape                   0
nucleus_shape                0
nuclear_cytoplasmic_ratio    0
chromatin_density            0
cytoplasm_vacuole            0
cytoplasm_texture            0
cytoplasm_colour             0
granule_type                 0
granule_colour               0
granularity                  0
dtype: int64

**Label and Feature Column Divide**

In [9]:
X = df.drop(columns=['label'])
y = df['label']